// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtWOjUyiPuj9qJMrDKdSCVAuXtRa3oT7E',
    appId: '1:441961526418:web:ceb9d080010f1d8f50a24b',
    messagingSenderId: '441961526418',
    projectId: 'flutterappdemo-74795',
    authDomain: 'flutterappdemo-74795.firebaseapp.com',
    storageBucket: 'flutterappdemo-74795.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXb6LFkr7SS37PUjGOad_C_Oc6BReoo_0',
    appId: '1:441961526418:android:95ebbad5e11ccffe50a24b',
    messagingSenderId: '441961526418',
    projectId: 'flutterappdemo-74795',
    storageBucket: 'flutterappdemo-74795.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPywW591DgSjTHclc4jKF7YBNPJioz-0w',
    appId: '1:441961526418:ios:f2a7618e30ef590950a24b',
    messagingSenderId: '441961526418',
    projectId: 'flutterappdemo-74795',
    storageBucket: 'flutterappdemo-74795.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPywW591DgSjTHclc4jKF7YBNPJioz-0w',
    appId: '1:441961526418:ios:f2a7618e30ef590950a24b',
    messagingSenderId: '441961526418',
    projectId: 'flutterappdemo-74795',
    storageBucket: 'flutterappdemo-74795.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtWOjUyiPuj9qJMrDKdSCVAuXtRa3oT7E',
    appId: '1:441961526418:web:e454251f614123c150a24b',
    messagingSenderId: '441961526418',
    projectId: 'flutterappdemo-74795',
    authDomain: 'flutterappdemo-74795.firebaseapp.com',
    storageBucket: 'flutterappdemo-74795.firebasestorage.app',
  );
}
